import requests
from urllib.parse import urljoin
import json

# Comprehensive test for Razorpay integration
def test_razorpay_full_flow():
    base_url = 'http://127.0.0.1:5000'

    # Create a session to maintain cookies
    session = requests.Session()

    print("=== Step 1: Login as customer ===")
    login_response = session.post(urljoin(base_url, '/login'), data={
        'email': 'customerdemo@gmail.com',
        'password': 'password123'
    })

    print(f"Login status: {login_response.status_code}")
    if login_response.status_code != 200:
        print("Login failed!")
        return

    # Check if we're redirected to dashboard (successful login)
    if 'dashboard' in login_response.url:
        print("✓ Login successful")
    else:
        print("✗ Login failed - not redirected to dashboard")
        return

    print("\n=== Step 2: Create pending order ===")
    # Simulate ordering from shop (shop_id=1)
    order_data = {
        'payment_method': 'Online Payment',
        'delivery_lat': '28.7041',
        'delivery_lng': '77.1025',
        'item_id': ['16'],  # Correct item ID for shop 7
        'quantity': ['1']
    }

    order_response = session.post(urljoin(base_url, '/shop/1'), data=order_data)
    print(f"Order creation status: {order_response.status_code}")

    # Check if redirected to payment page
    if 'payment' in order_response.url:
        print("✓ Pending order created successfully")
    else:
        print("✗ Failed to create pending order")
        print(f"Response URL: {order_response.url}")
        return

    print("\n=== Step 3: Test Razorpay order creation ===")
    razorpay_response = session.post(urljoin(base_url, '/api/create-razorpay-order'))
    print(f"Razorpay order creation status: {razorpay_response.status_code}")

    if razorpay_response.status_code == 200:
        try:
            order_data = razorpay_response.json()
            print("✓ Razorpay order created successfully")
            print(f"Order ID: {order_data.get('order_id')}")
            print(f"Amount: {order_data.get('amount')}")
            print(f"Key: {order_data.get('key')[:10]}...")  # Partial key for security

            # Simulate successful payment (in real scenario, this would come from Razorpay)
            print("\n=== Step 4: Test payment verification ===")
            verify_data = {
                'razorpay_order_id': order_data['order_id'],
                'razorpay_payment_id': 'pay_test_payment_id_123',  # Mock payment ID
                'razorpay_signature': 'test_signature'  # This would be generated by Razorpay
            }

            verify_response = session.post(
                urljoin(base_url, '/api/verify-payment'),
                json=verify_data
            )
            print(f"Payment verification status: {verify_response.status_code}")
            print(f"Response: {verify_response.text}")

        except json.JSONDecodeError:
            print("✗ Invalid JSON response from Razorpay API")
            print(f"Response text: {razorpay_response.text}")
    else:
        print("✗ Failed to create Razorpay order")
        print(f"Response: {razorpay_response.text}")

if __name__ == "__main__":
    test_razorpay_full_flow()